# Generated by Django 3.1.4 on 2020-12-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20201225_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ts_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ts_images_seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='uniform_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='uniform_images_seen',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
