# Generated by Django 3.1.4 on 2020-12-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20201226_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='demo_completed',
            field=models.BooleanField(default=False),
        ),
    ]
