# Generated by Django 3.1.4 on 2020-12-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20201227_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='code',
        ),
    ]
