# Generated by Django 3.1.4 on 2020-12-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20201228_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='sampling_type',
            field=models.CharField(choices=[('ts', 'Double Thompson Sampling'), ('un', 'Uniform Sampling')], default='un', max_length=2),
        ),
        migrations.CreateModel(
            name='DuelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_arm', models.IntegerField()),
                ('second_arm', models.IntegerField()),
                ('first_arm_wins', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('first_arm', 'second_arm')},
            },
        ),
    ]
