# Generated by Django 3.1.4 on 2020-12-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20201229_1930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duelrecord',
            unique_together=set(),
        ),
    ]
