# Generated by Django 3.1.4 on 2020-12-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20201229_1940'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='duelrecord',
            constraint=models.UniqueConstraint(fields=('first_arm', 'second_arm'), name='unique_duels'),
        ),
    ]
