# Generated by Django 3.1.4 on 2020-12-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelrecord',
            name='second_arm_wins',
            field=models.IntegerField(default=0),
        ),
    ]
