# Generated by Django 3.1.4 on 2021-01-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_duelrecord_second_arm_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelrecord',
            name='first_arm',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='duelrecord',
            name='second_arm',
            field=models.IntegerField(db_index=True),
        ),
    ]
